# Generated by Django 3.0.1 on 2019-12-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lkl_lat', models.FloatField(null=True)),
                ('lkl_lng', models.FloatField(null=True)),
                ('pictures', models.TextField(blank=True)),
            ],
        ),
    ]
